// Copyright 2017 David Lavieri.  All rights reserved.
// Use of this source code is governed by a MIT License
// License that can be found in the LICENSE file.

export default {
  MAINHEADER_MESSAGES_TOGGLE: 'MAINHEADER_MESSAGES_TOGGLE',
  MAINHEADER_NOTIFICATIONS_TOGGLE: 'MAINHEADER_NOTIFICATIONS_TOGGLE',
  MAINHEADER_TASKS_TOGGLE: 'MAINHEADER_TASKS_TOGGLE',
  MAINHEADER_USER_TOGGLE: 'MAINHEADER_USER_TOGGLE'
}
